---
- hosts:webserver
  become: true
  tasks:

- name: Install packages
  yum:
    name: "{{item}}"
    state: present   
  with_items:
    - java-1.8.0
    - tomcat-webapps
    - tomcat-admin-webapps
      
- name: copy tomcat user file to tomcat server
  copy:
    src: tomcat-users.xml
    dest: /etc/tomcat/tomcat-user.xml

- name: Deploy Artifacts to tomcat server
  get_url:
    url: http://44.242.137.227:8081/repository/GAME/dev/dev/1.1/dev-1.1.war
    url_username: admin
    password: 1234
    dest: /usr/share/tomcat/webapps/
