name: Maven Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: |
        echo Running Maven Action to Build!
        echo $GITHUB_WORKSPACE
        ls gameoflife-web
  # ls game-of-life
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk  
    - run: |
        mvn -f pom.xml clean package
        echo $GITHUB_WORKSPACE
        ls gameoflife-web/target 
        
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v1
      with:
    # Publish profile (*.publishsettings) file contents with Web Deploy secrets
        publish-profile: ${{secrets.azureWebappPublishProfile}}
    # Name of the Azure Web App
        app-name: tommycat
    # Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
        package: gameoflife-web/target/*.war
    # Enter an existing Slot other than the Production slot
    #   slot-name: # optional, default is production
